config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update,] do
  	member do
     get :following, :followers
    end
	end

  resources :books do
	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about'
  get "search" => "search#search"
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: { in: 2..20 }

  validates :introduction, length: { maximum: 50 }

  include JpPrefecture
  jp_prefecture :prefecture_code

  #postal_codeからprefecture_nameに変換するメソッドを用意します．
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def User.search(search, user_or_post, how_search)
    if user_or_post == "1"
      if how_search == "1"
          User.where(['name LIKE ?', "%#{search}%"])
      elsif how_search == "2"
          User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "3"
          User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "4"
          User.where(['name LIKE ?', "#{search}"])
      else
      User.all
      end
    end
  end

  def address
    [postal_code, city, building].compact.join(',')
  end
  geocoded_by :address
  after_validation :geocode
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, :only => [:show, :index, :edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render action: :edit
  	end
  end

  def following
    @book = Book.new
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followers
    @book = Book.new
    @user = User.find(params[:id])
    @users = @user.follower_user
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image ,:prefecture_code, :city, :building, :postal_code)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<td><%= link_to "フォロー数: #{user.follower.count}", following_user_path(user) %></td>
		<td><%= link_to "フォロワー数: #{user.followed.count}", followers_user_path(user) %></td>
	</tr>
	<tr>
		<td>
		<% if user != current_user %>
		<% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-warning" %>
      	<% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-success" %>
      	<% end %>
      	<% end %>
      	</td>
	</tr>
</table>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div data-turbolinks="false">
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %><br>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %><br>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %><br>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="field">
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code, autofocus: true, placeholder: 'postal_code', class: "postal_code", id: "address_zipcode" %>
  </div>

<div class="field">
    <%= f.label :prefecture_code %><br>
    <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :name, :name, class: "address" %><br>
    <%= f.text_field :city, autofocus: true, placeholder: 'ciry', class: "address", id:"address_city" %><br>
    <%= f.text_field :building, autofocus: true, placeholder: 'building', class: "address", id: "address_street" %><br>
  </div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>
</div>

app/views/users/followers.html.erb
<div class="container">

<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>

</div>

<div class="col-xs-9">

<h2>follwerd users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg", size: "50x50") %></td>
			<td><%= user.name%></td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
			<td><%= "フォロー数: #{user.follower.count}" %></td>
			<td><%= "フォロワー数: #{user.followed.count}" %></td>
			<td><% if current_user.following?(user) %>
        		<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      			<% else %>
        		<%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      			<% end %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->

</div>
</div>

app/views/users/following.html.erb
<div class="container">

<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>

</div>

<div class="col-xs-9">

<h2>follow users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg", size: "50x50") %></td>
			<td><%= user.name%></td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
			<td><%= "フォロー数: #{user.follower.count}" %></td>
			<td><%= "フォロワー数: #{user.followed.count}" %></td>
			<td><% if current_user.following?(user) %>
        		<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      			<% else %>
        		<%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      			<% end %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->

</div>
</div>

app/views/users/index.html.erb
<div class="container">

<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>

</div>

<div class="col-xs-9">

<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->

</div>
</div>

app/views/users/show.html.erb
<div class="container">

<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>

</div>

<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td><%= book.book_comments.count %>件コメント</td></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--books一覧 -->
<script type="text/javascript">
  	function initMap() {
	//latitude,longitudeから位置を特定
	    var test ={lat: <%= @user.latitude %>, lng: <%= @user.longitude %>};
	    var map = new google.maps.Map(document.getElementById('map'), {
	              zoom: 15,
	              center: test
	              });
	    var transitLayer = new google.maps.TransitLayer();
	    transitLayer.setMap(map);

	 //Map上の指定した位置にピンを挿して表示する
	    var marker = new google.maps.Marker({
	                  position:test,
	                  map: map,
	    });
	};
</script>

	<!--以下の記述の中にあるYOUR_API_KEYには取得したご自身のAPIキーを記述してください-->
<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>
<!--表示するmapのcssです。ご自身でカスタマイズしてください。高さが設定されていないと表示されないことがあります。-->
<style type="text/css">
  #map { height: 350px;
         width: 85%;}
</style>

<% if @user == current_user %>
<!--mapの表示-->
<h2>Your Map</h2>
<div id="map"></div>
<% end %>
</div>
</div>