config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update,] do
  	member do
     get :following, :followers
    end
	end

  resources :books do
	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about'
  get "search" => "search#search"
  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    def Book.search(search, user_or_post, how_search)
    if user_or_post == "2"
    	if how_search == "1"
         	Book.where(['title LIKE ?', "%#{search}%"])
      	elsif how_search == "2"
          	Book.where(['title LIKE ?', "%#{search}"])
      	elsif how_search == "3"
          	Book.where(['title LIKE ?', "#{search}%"])
      	elsif how_search == "4"
        	Book.where(['title LIKE ?', "#{search}"])
    	else
      	Book.all
    	end
	end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, :only => [:show, :index, :edit]


  def show
    @newbook = Book.new
  	@book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @book = Book.new
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comments.html.erb
<div data-turbolinks="false">
<table id="comments" class="table table-hover table-inverse">
	<% book.book_comments.each do |book_comment| %>
		<tr id="comment-<%= book_comment.id %>">
			<td><%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg", size: "50x50") %></td>
			<td><%= book_comment.user.name %></td>
			<td><%= book_comment.comment %></td>
			<td>
				<% if book_comment.user == current_user%>
			  		<div>
    					<%= link_to "Destroy", book_book_comment_path(book,book_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
			  		</div>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>
</div>

app/views/books/_favorite.html.erb
<div data-turbolinks="false">
<% if book.favorited_by?(current_user) %>
        <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
    	<%= book.favorites.count %>
    	<% end %>
	<% else %>
    	<%= link_to book_favorites_path(book), method: :post, remote: true do %>
    	<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
    	<%= book.favorites.count %>
        <% end %>
    <% end %>
</div>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg", size: "50x50") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<div id="favorite-<%= book.id %>">
						<%= render 'favorites/favorite', book: book %>
						</div>
					</td>
					<td>
						<%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :opinion %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-warning">
  	<%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <% end %>
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-warning">
  	<%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <% end %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<%= render 'books/index', books: @books %>
		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @newbook %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<td>
						<div id="favorite-<%= @book.id %>">
						<%= render 'favorites/favorite', book: @book %>
						</div></td>
						<td>
        				<%= @book.book_comments.count %>件コメント</td>


					<% if @user.id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
			<%= render 'books/comments', book: @book %>
			<div class="row">
			<div class="col-sm-6">
			<%= form_with(model: [@book, @book_comment], remote:true) do |f| %>
    		<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %><br>
   			<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
   			</div>
			</div>
<% end %>

	</div>
</div>